apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "true"
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Values.cluster.name }}-chart-operator
  namespace: {{ .Release.Namespace }}
spec:
  catalog: default
  {{- include "kubeconfig" . | nindent 2 }}
  {{- include "config" . | nindent 2 }}
  name: chart-operator
  namespace: giantswarm
  version: 2.19.1
