apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "true"
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Values.cluster.name }}-node-exporter
  namespace: {{ .Release.Namespace }}
spec:
  catalog: default
  {{- include "kubeconfig" . | nindent 2 }}
  {{- include "config" . | nindent 2 }}
  name: node-exporter-app
  namespace: kube-system
  version: 1.8.0
